# Generated by Django 3.2.5 on 2021-07-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0002_rename_image_home_images_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='img',
            new_name='imghome',
        ),
    ]
