# Generated by Django 3.2.5 on 2021-07-20 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0003_rename_img_images_imghome'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='about_us_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pic'),
            preserve_default=False,
        ),
    ]
