# Generated by Django 3.2.5 on 2021-07-22 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0004_images_about_us_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='तसबीर',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pic'),
            preserve_default=False,
        ),
    ]
