# Generated by Django 3.2.5 on 2021-07-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0005_post_तसबीर'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='imghome',
            new_name='तसबीर',
        ),
    ]
