# Generated by Django 3.2.5 on 2021-07-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0006_rename_imghome_images_तसबीर'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='तसबीर',
            new_name='imghome',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='तसबीर',
            new_name='post_img',
        ),
    ]
