# Generated by Django 3.2.5 on 2021-07-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0007_auto_20210722_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_img',
            new_name='imghome',
        ),
    ]
