# Generated by Django 3.2.5 on 2021-07-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0008_rename_post_img_post_imghome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='imghome',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='imghome',
            new_name='image',
        ),
    ]
