# Generated by Django 3.2.5 on 2021-07-22 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0010_auto_20210722_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pic'),
            preserve_default=False,
        ),
    ]
