# Generated by Django 3.2.5 on 2021-09-06 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0012_post_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='profileimage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pic'),
            preserve_default=False,
        ),
    ]
