# Generated by Django 3.2.5 on 2021-09-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0013_images_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='booksimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
