# Generated by Django 3.2.5 on 2021-09-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0015_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='picks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('book_name', models.CharField(max_length=50, null=True)),
                ('writer', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
