# Generated by Django 3.2.5 on 2021-09-29 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0016_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pic'),
            preserve_default=False,
        ),
    ]
