# Generated by Django 3.2.5 on 2021-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0018_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pic')),
                ('category', models.CharField(max_length=50)),
                ('article', models.TextField(null=True)),
            ],
        ),
    ]
