# Generated by Django 3.2.5 on 2021-10-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0019_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('adress', models.TextField(null=True)),
                ('contact', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
