# Generated by Django 3.2.5 on 2021-10-07 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0021_auto_20211006_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='fb',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='linkedin',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='twitter',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
