# Generated by Django 3.2.5 on 2021-10-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0022_auto_20211007_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writter',
            field=models.TextField(null=True),
        ),
    ]
