# Generated by Django 3.2.5 on 2021-10-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0023_post_writter'),
    ]

    operations = [
        migrations.CreateModel(
            name='newrelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='logo',
        ),
    ]
