# Generated by Django 3.2.5 on 2021-10-09 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0024_auto_20211009_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newrelease',
            old_name='name',
            new_name='book_name',
        ),
        migrations.AddField(
            model_name='newrelease',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
