# Generated by Django 3.2.5 on 2021-10-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0025_auto_20211009_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newrelease',
            old_name='writer',
            new_name='writter',
        ),
    ]
