# Generated by Django 3.2.5 on 2021-10-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0026_rename_writer_newrelease_writter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrelease',
            name='paragraph',
            field=models.TextField(null=True),
        ),
    ]
