# Generated by Django 3.2.5 on 2021-10-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0027_newrelease_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writter', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
