# Generated by Django 3.2.5 on 2021-10-09 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sumarga_app', '0028_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='bg_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pic'),
            preserve_default=False,
        ),
    ]
